roles:
  student: 133146593, 38407435
  korrektor: 133146593, 38407435
  organisator: 133146593, 38407435

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GitHubClientID}
            client-secret: ${GitHubClientSecret}
            scope: read:public_repo
  datasource:
    password: mypassword123
    username: user
    url: jdbc:postgresql://localhost:5432/postgres