spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GitHubClientID}
            client-secret: ${GitHubClientSecret}
            scope: read:public_repo